language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_geocoder/ framework/app/libraries/li3_geocoder
  - cd framework
  - git submodule update --init --recursive
  - cd app/libraries/li3_geocoder
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

script: ../../../libraries/lithium/console/li3 test tests
